server:
  port: 18080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/security?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 251067417328-hmbpagmvne63bmlvkvr6e9ub9k65ifo5.apps.googleusercontent.com
            client-secret: fjJsMK695R2a3hdL_2aAszRQ
            scope:
              - email
              - profile

          facebook:
            client-id: 5621262121231904
            client-secret: 407621277f9c6c60020d23ef6d838545
            scope:
              - email
              - public_profile # https://developers.facebook.com/docs/facebook-login/web/ (샘플 명세서에 있음)

          naver:
            client-id: 78RUY8DL4__eoaIX1GW6
            client-secret: 2BlHze6b3e
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:18080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.